// Generated by CoffeeScript 2.7.0
var PLUGIN_ID, PLUGIN_SCRIPT_SRC, UBHD3DViewerPlugin, ref, sortVariants;

PLUGIN_ID = 'fylr-plugin-ubhd-3d-viewer';

PLUGIN_SCRIPT_SRC = typeof document !== 'undefined' ? (ref = document.currentScript) != null ? ref.src : void 0 : null;

UBHD3DViewerPlugin = class UBHD3DViewerPlugin extends AssetDetail {
  constructor(...args) {
    super(...args);
    this.viewerModulePromise = null;
  }

  normalizeElement(target) {
    if (target == null) {
      return null;
    }
    if (target.jquery != null) {
      return target[0];
    }
    if (typeof target.get === 'function') {
      return target.get(0);
    }
    return target;
  }

  getPluginScript() {
    var ref1;
    if (((ref1 = document.currentScript) != null ? ref1.src : void 0) != null) {
      return document.currentScript;
    }
    return Array.from(document.scripts).find(function(script) {
      return /(UBHD3DViewerPlugin(?:\.coffee)?|fylr-plugin-ubhd-3d-viewer)\.js(?:[?#].*)?$/.test(script.src || '');
    });
  }

  normalizePluginBaseUrl(value) {
    var err, url;
    if (!value) {
      return null;
    }
    try {
      url = new URL(value, window.location.href);
      if (/\/$/.test(url.pathname)) {
        return url.href;
      }
      return new URL('./', url.href).href;
    } catch (error1) {
      err = error1;
      return null;
    }
  }

  getPluginBaseUrl() {
    var normalized, pluginBaseUrl, ref1, ref2, script;
    pluginBaseUrl = typeof ez5 !== "undefined" && ez5 !== null ? (ref1 = ez5.pluginManager) != null ? typeof ref1.getPlugin === "function" ? (ref2 = ref1.getPlugin(PLUGIN_ID)) != null ? typeof ref2.getBaseURL === "function" ? ref2.getBaseURL() : void 0 : void 0 : void 0 : void 0 : void 0;
    normalized = this.normalizePluginBaseUrl(pluginBaseUrl);
    if (normalized != null) {
      return normalized;
    }
    normalized = this.normalizePluginBaseUrl(PLUGIN_SCRIPT_SRC);
    if (normalized != null) {
      return normalized;
    }
    script = this.getPluginScript();
    return this.normalizePluginBaseUrl(script != null ? script.src : void 0);
  }

  getViewerUrls() {
    var pluginBaseUrl;
    pluginBaseUrl = this.getPluginBaseUrl();
    if (pluginBaseUrl == null) {
      return null;
    }
    return {
      pageUrl: new URL('viewer-dist/', pluginBaseUrl).href
    };
  }

  ensureViewerStylesheet(cssUrl) {
    var existingLink, link;
    if (cssUrl == null) {
      return;
    }
    existingLink = document.querySelector(`link[data-ubhd-viewer-css='${cssUrl}']`);
    if (existingLink != null) {
      return;
    }
    link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = cssUrl;
    link.dataset.ubhdViewerCss = cssUrl;
    return document.head.appendChild(link);
  }

  importViewerModule(moduleUrl) {
    if (this.viewerModulePromise == null) {
      this.viewerModulePromise = Function('url', 'return import(url)')(moduleUrl);
    }
    return this.viewerModulePromise;
  }

  __probeUrlStatus(url) {
    return new Promise(function(resolve) {
      var err, getOpts, headOpts, ref1;
      if (!url) {
        return resolve(null);
      }
      try {
        if (window.fetch != null) {
          headOpts = {
            method: 'HEAD',
            cache: 'no-store',
            credentials: 'include'
          };
          getOpts = {
            method: 'GET',
            cache: 'no-store',
            credentials: 'include',
            headers: {
              'Range': 'bytes=0-0'
            }
          };
          fetch(url, headOpts).then(function(res) {
            var status;
            status = res.status;
            if (status === 405 || status === 501) {
              return fetch(url, getOpts).then(function(r2) {
                return resolve(r2.status);
              }).catch(function(_) {
                return resolve(null);
              });
            } else {
              return resolve(status);
            }
          }).catch(function(_) {
            return fetch(url, getOpts).then(function(r2) {
              return resolve(r2.status);
            }).catch(function(__) {
              return resolve(null);
            });
          });
          return;
        }
        if (((ref1 = window.$) != null ? ref1.ajax : void 0) != null) {
          $.ajax({
            url: url,
            type: 'HEAD',
            cache: false,
            xhrFields: {
              withCredentials: true
            }
          }).done(function(_) {
            return resolve(200);
          }).fail(function(xhr, _status, _err) {
            var ref2;
            return resolve((ref2 = xhr != null ? xhr.status : void 0) != null ? ref2 : null);
          });
          return;
        }
      } catch (error1) {
        err = error1;
      }
      // ignore
      return resolve(null);
    });
  }

  __pickFirstAccessible(assetInfos) {
    return new Promise((resolve) => {
      var candidates, checkNext, idx, unknown;
      candidates = (assetInfos || []).filter(function(assetInfo) {
        return assetInfo != null ? assetInfo.url : void 0;
      });
      if (!candidates.length) {
        return resolve(null);
      }
      unknown = [];
      idx = 0;
      checkNext = () => {
        var candidate, ref1;
        if (idx >= candidates.length) {
          return resolve((ref1 = unknown[0]) != null ? ref1 : null);
        }
        candidate = candidates[idx];
        idx += 1;
        return this.__probeUrlStatus(candidate.url).then((status) => {
          if (typeof status === 'number' && status >= 200 && status < 400) {
            return resolve(candidate);
          } else if (status === 403 || status === 404 || status === 0) {
            return checkNext();
          } else if (status != null) {
            return checkNext();
          } else {
            unknown.push(candidate);
            return checkNext();
          }
        }).catch((_) => {
          unknown.push(candidate);
          return checkNext();
        });
      };
      return checkNext();
    });
  }

  __bestVersionUrl(version) {
    var ref1, ref2, ref3, ref4;
    if (version == null) {
      return null;
    }
    if (version.url != null) {
      return version.url;
    }
    if (((ref1 = version.versions) != null ? (ref2 = ref1.original) != null ? ref2.url : void 0 : void 0) != null) {
      return (ref3 = version.versions) != null ? (ref4 = ref3.original) != null ? ref4.url : void 0 : void 0;
    }
    return null;
  }

  __sameOriginUrl(rawUrl) {
    var err, u;
    if (!rawUrl) {
      return rawUrl;
    }
    try {
      u = new URL(rawUrl, window.location.href);
      if (u.origin !== window.location.origin) {
        return u.pathname + u.search + u.hash;
      }
      return u.href;
    } catch (error1) {
      err = error1;
      return rawUrl;
    }
  }

  __withAccessToken(rawUrl) {
    var err, isApiUrl, ref1, separator, token, u;
    if (!rawUrl) {
      return rawUrl;
    }
    token = typeof ez5 !== "undefined" && ez5 !== null ? (ref1 = ez5.session) != null ? ref1.token : void 0 : void 0;
    if (!token) {
      return rawUrl;
    }
    try {
      u = new URL(rawUrl, window.location.href);
      isApiUrl = u.origin === window.location.origin && u.pathname.indexOf('/api/') === 0;
      if (!isApiUrl) {
        return rawUrl;
      }
      if (!u.searchParams.get('access_token')) {
        u.searchParams.set('access_token', token);
      }
      return u.pathname + u.search + u.hash;
    } catch (error1) {
      err = error1;
      separator = rawUrl.indexOf('?') === -1 ? '?' : '&';
      return rawUrl + separator + 'access_token=' + encodeURIComponent(token);
    }
  }

  __processVersion(version) {
    var assetInfo, ref1, ref2, ref3, ref4, url;
    assetInfo = {
      type: null,
      url: null,
      extension: null,
      prio: null,
      defaults: ''
    };
    if (version == null) {
      return false;
    }
    if (version.name === 'gltf' && version.class_extension === 'archive.unpack.zip') {
      assetInfo.type = 'gltf';
      assetInfo.prio = 5;
      assetInfo.url = ((ref1 = version.versions) != null ? (ref2 = ref1.directory) != null ? ref2.url : void 0 : void 0) + '/model.gltf';
      assetInfo.extension = (ref3 = version.versions) != null ? (ref4 = ref3.original) != null ? ref4.extension : void 0 : void 0;
      if (assetInfo.url != null) {
        return assetInfo;
      }
    }
    if (version.extension === 'glb') {
      url = this.__bestVersionUrl(version);
      if (url != null) {
        assetInfo.type = 'gltf';
        assetInfo.url = url;
        assetInfo.extension = version.extension;
        assetInfo.prio = 5;
        return assetInfo;
      }
    }
    if (version.extension === 'gltf') {
      url = this.__bestVersionUrl(version);
      if (url != null) {
        assetInfo.type = 'gltf';
        assetInfo.url = url;
        assetInfo.extension = version.extension;
        assetInfo.prio = 4;
        return assetInfo;
      }
    }
    return false;
  }

  __easUrl(asset) {
    var alternative, assetInfo, candidates, defaults, hasTypeWithoutUrl, i, j, k, len, len1, len2, processed, ref1, ref2, ref3, ref4, sorted, variant, variants, version;
    assetInfo = {
      type: null,
      url: null,
      extension: null,
      defaults: '',
      alternatives: []
    };
    if (!asset) {
      return assetInfo;
    }
    variants = asset instanceof Asset ? asset.getSiblingsFromData() : Object.values(asset);
    if (!variants) {
      return assetInfo;
    }
    candidates = [];
    defaults = null;
    hasTypeWithoutUrl = false;
    for (i = 0, len = variants.length; i < len; i++) {
      variant = variants[i];
      ref1 = Object.values(variant.versions || {});
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        version = ref1[j];
        if (version.original_filename === '3D_viewer.json') {
          defaults = (ref2 = version.versions) != null ? (ref3 = ref2.original) != null ? ref3.url : void 0 : void 0;
        } else {
          processed = this.__processVersion(version);
          if (processed && processed.type && !processed.url) {
            hasTypeWithoutUrl = true;
          }
          if (processed && processed.url) {
            candidates.push(processed);
          }
        }
      }
    }
    if (candidates.length > 0) {
      sorted = candidates.sort(sortVariants);
      assetInfo = sorted[0];
      if (defaults) {
        assetInfo.defaults = defaults;
      }
      assetInfo.alternatives = sorted.slice(1);
      ref4 = assetInfo.alternatives;
      for (k = 0, len2 = ref4.length; k < len2; k++) {
        alternative = ref4[k];
        if (defaults) {
          alternative.defaults = defaults;
        }
      }
      return assetInfo;
    }
    if (hasTypeWithoutUrl) {
      assetInfo.type = 'pending';
      if (defaults) {
        assetInfo.defaults = defaults;
      }
    }
    return assetInfo;
  }

  getButtonLocaKey(asset) {
    var assetInfo;
    assetInfo = this.__easUrl(asset != null ? asset : this.asset);
    if (!(assetInfo.url || assetInfo.type)) {
      assetInfo = this.fallbackAssetInfo(asset != null ? asset : this.asset);
    }
    if (!(assetInfo.url || assetInfo.type)) {
      return;
    }
    return 'ubhd.asset.detail.360degrees';
  }

  __fetchFullAssetInfo() {
    var assetId, ref1, ref2;
    assetId = (ref1 = this.asset) != null ? (ref2 = ref1.value) != null ? ref2._id : void 0 : void 0;
    if (!assetId) {
      return null;
    }
    return ez5.api.eas({
      type: 'GET',
      data: {
        ids: JSON.stringify([assetId]),
        format: 'long'
      }
    });
  }

  startAutomatically() {
    return true;
  }

  getExtension(url) {
    var match;
    if (typeof url !== 'string') {
      return null;
    }
    match = url.toLowerCase().match(/\.([a-z0-9]+)(?:$|[?#])/);
    if (match) {
      return match[1];
    } else {
      return null;
    }
  }

  collectModelUrlCandidates(value, seen = new WeakSet(), depth = 0, path = [], results = []) {
    var extension;
    if (depth > 7 || (value == null)) {
      return results;
    }
    if (typeof value === 'string') {
      extension = this.getExtension(value);
      if (extension === 'glb' || extension === 'gltf') {
        results.push({
          url: value,
          extension: extension,
          path: path.slice()
        });
      }
      return results;
    }
    if (typeof value !== 'object') {
      return results;
    }
    if (seen.has(value)) {
      return results;
    }
    seen.add(value);
    if (Array.isArray(value)) {
      value.forEach((item, index) => {
        return this.collectModelUrlCandidates(item, seen, depth + 1, path.concat([`${index}`]), results);
      });
      return results;
    }
    Object.entries(value).forEach(([key, nestedValue]) => {
      return this.collectModelUrlCandidates(nestedValue, seen, depth + 1, path.concat([key]), results);
    });
    return results;
  }

  scoreModelCandidate(candidate) {
    var pathText, score;
    pathText = candidate.path.join('.').toLowerCase();
    score = candidate.extension === 'glb' ? 120 : 110;
    if (/(^|\.)(url|href|download|downloadurl|file|original|source|target)$/.test(pathText)) {
      score += 40;
    }
    if (/(version|versions|derived|files|asset|original|source)/.test(pathText)) {
      score += 20;
    }
    if (/(preview|poster|thumbnail|thumb|icon|logo|image)/.test(pathText)) {
      score -= 120;
    }
    return score;
  }

  fallbackAssetInfo(asset) {
    var bestCandidate, candidates, ref1, source;
    source = (ref1 = asset != null ? asset.value : void 0) != null ? ref1 : asset;
    candidates = this.collectModelUrlCandidates(source);
    if (!candidates.length) {
      return null;
    }
    bestCandidate = candidates.map((candidate) => {
      return Object.assign({}, candidate, {
        score: this.scoreModelCandidate(candidate)
      });
    }).sort(function(left, right) {
      return right.score - left.score;
    })[0];
    if (!(bestCandidate != null ? bestCandidate.url : void 0)) {
      return null;
    }
    return {
      type: 'gltf',
      url: bestCandidate.url,
      extension: bestCandidate.extension,
      prio: bestCandidate.extension === 'glb' ? 5 : 4,
      defaults: '',
      alternatives: []
    };
  }

  createViewerContainer(target) {
    var canvas, container;
    container = this.normalizeElement(target);
    if (container == null) {
      return null;
    }
    container.innerHTML = '';
    container.style.minHeight = '480px';
    canvas = document.createElement('canvas');
    canvas.className = 'webgl';
    container.appendChild(canvas);
    return {
      container: container,
      canvas: canvas
    };
  }

  __mountViewer(target, assetInfo) {
    var container, iframe, pageUrl, urls;
    urls = this.getViewerUrls();
    if ((urls != null ? urls.pageUrl : void 0) == null) {
      console.error('[UBHD3DViewerPlugin] Unable to determine viewer asset URLs.');
      return Promise.resolve(null);
    }
    container = this.normalizeElement(target);
    if (container == null) {
      return Promise.resolve(null);
    }
    container.innerHTML = '';
    container.style.minHeight = '480px';
    iframe = document.createElement('iframe');
    iframe.id = 'threeiframe';
    iframe.setAttribute('frameborder', '0');
    iframe.setAttribute('scrolling', 'no');
    iframe.style.width = '100%';
    iframe.style.minHeight = '480px';
    iframe.style.border = '0';
    pageUrl = new URL(urls.pageUrl);
    pageUrl.searchParams.set('asset', (assetInfo != null ? assetInfo.url : void 0) || '');
    if (assetInfo != null ? assetInfo.defaults : void 0) {
      pageUrl.searchParams.set('config', assetInfo.defaults);
    }
    iframe.src = pageUrl.href;
    container.appendChild(iframe);
    return Promise.resolve(iframe);
  }

  createMarkup() {
    var assetInfo, request;
    super.createMarkup();
    assetInfo = this.__easUrl(this.asset);
    if (!(assetInfo.url || assetInfo.type)) {
      assetInfo = this.fallbackAssetInfo(this.asset);
    }
    request = this.__fetchFullAssetInfo();
    if (request != null) {
      request.done((assetServerData) => {
        if (assetServerData != null ? assetServerData.error : void 0) {
          if (assetInfo.url) {
            this.__createMarkup(assetInfo);
          }
          return;
        }
        return this.__createMarkup(null, assetServerData);
      }).fail(() => {
        if (assetInfo.url) {
          return this.__createMarkup(assetInfo);
        }
      });
      return;
    }
    if (!assetInfo.url && assetInfo.type) {
      return;
    }
    if (assetInfo.url) {
      this.__createMarkup(assetInfo);
    }
  }

  __createMarkup(assetInfo, assetServerData) {
    var allCandidates, viewerDiv;
    if (!assetInfo && assetServerData) {
      assetInfo = this.__easUrl(assetServerData);
      if (!((assetInfo != null ? assetInfo.url : void 0) && (assetInfo != null ? assetInfo.type : void 0))) {
        assetInfo = this.fallbackAssetInfo(assetServerData);
      }
      if (!((assetInfo != null ? assetInfo.url : void 0) && (assetInfo != null ? assetInfo.type : void 0))) {
        return;
      }
    }
    assetInfo.url = this.__sameOriginUrl(assetInfo.url);
    assetInfo.url = this.__withAccessToken(assetInfo.url);
    if (assetInfo.defaults) {
      assetInfo.defaults = this.__sameOriginUrl(assetInfo.defaults);
    }
    if (assetInfo.defaults) {
      assetInfo.defaults = this.__withAccessToken(assetInfo.defaults);
    }
    assetInfo.alternatives = (assetInfo.alternatives || []).map((alternative) => {
      if (!(alternative != null ? alternative.url : void 0)) {
        return alternative;
      }
      alternative.url = this.__sameOriginUrl(alternative.url);
      alternative.url = this.__withAccessToken(alternative.url);
      if (alternative.defaults) {
        alternative.defaults = this.__sameOriginUrl(alternative.defaults);
      }
      if (alternative.defaults) {
        alternative.defaults = this.__withAccessToken(alternative.defaults);
      }
      return alternative;
    });
    viewerDiv = CUI.dom.element('div', {
      id: 'ubhd3d'
    });
    CUI.dom.append(this.outerDiv, viewerDiv);
    allCandidates = [assetInfo].concat(assetInfo.alternatives || []);
    this.__pickFirstAccessible(allCandidates).then((chosen) => {
      if (!chosen) {
        viewerDiv.textContent = '3D-Datei kann mit den aktuellen Rechten nicht geladen werden.';
        return;
      }
      return this.__mountViewer(viewerDiv, chosen).catch((error) => {
        console.error('[UBHD3DViewerPlugin] Failed to mount embedded viewer.', error);
        return viewerDiv.textContent = '3D-Datei kann derzeit nicht geladen werden.';
      });
    }).catch((_) => {
      return viewerDiv.textContent = '3D-Datei kann derzeit nicht geladen werden.';
    });
  }

};

if (typeof window !== 'undefined') {
  window.UBHD3DViewerPlugin = UBHD3DViewerPlugin;
}

sortVariants = function(a, b) {
  if (a.prio && b.prio) {
    return b.prio - a.prio;
  } else if (a.prio) {
    return -1;
  } else if (b.prio) {
    return 1;
  } else {
    return 0;
  }
};

ez5.session_ready(() => {
  var ref1, ref2;
  if (typeof AssetBrowser !== "undefined" && AssetBrowser !== null) {
    if ((ref1 = AssetBrowser.plugins) != null) {
      if (typeof ref1.registerPlugin === "function") {
        ref1.registerPlugin(UBHD3DViewerPlugin);
      }
    }
  }
  return (ref2 = ez5.pluginManager.getPlugin('fylr-plugin-ubhd-3d-viewer')) != null ? typeof ref2.loadCss === "function" ? ref2.loadCss() : void 0 : void 0;
});
